% Init some constants
a = 1/sqrt(2);
b = 1/sqrt(10);
c = 3/sqrt(10);
d = 1/sqrt(42);
e = 3/sqrt(42);
f = 5/sqrt(42);
g = 7/sqrt(42);

% Init constellations
bpsk = [a+a, -a-a];
qpsk = [a+a, a-a, -a+a, -a-a];
qam_16 = [...
    b+b, b+c, c+b, c+c, b-b, b-c, c-b, c-c,...
    -b+b, -b+c, -c+b, -c+c, -b-b, -b-c, -c-b, -c-c];
qam_64 = [...
    e+e, e+d, d+e, d+d, e+f, e+g, d+f, d+g,...
    f+e, f+d, g+e, g+d, f+f, f+g, g+f, g+g,...
    e-e, e-d, d-e, d-d, e-f, e-g, d-f, d-g,...
    f-e, f-d, g-e, g-d, f-f, f-g, g-f, g-g,...
    -e+e, -e+d -d+e, -d+d, -e+f,-e+g, -d+f, -d+g,...
    -f+e, -f+d, -g+e, -g+d, -f+f, -f+g, -g+f, -g+g,...
    -e-e, -e-d, -d-e, -d-d,-e-f, -e-g, -d-f, -d-g,...
    -f-e, -f-d, -g-e, -g-d,-f-f, -f-g, -g-f, -g-g];